name: Sync to Hugging Face hub
on:
  repository_dispatch:
    types:
      - manual-trigger-all
  push:
    branches:
      - main

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: sync to huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
        run: |
          npm i
          npm run build
          git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME --depth=1 target
          find target -maxdepth 1 -regextype posix-egrep ! -iregex 'target/?(|README.md|.git|.gitignore)' | xargs rm -rf
          mv out/* target
          cd target
          git config user.name $HF_USERNAME
          git config user.email $HF_USERNAME@huggingface.co
          git add -A
          git commit -am "auto deploy"
          git push origin main -f
